# Generated by Django 4.1.2 on 2023-01-19 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_like_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='datetime',
        ),
    ]
