# Generated by Django 4.1.2 on 2023-03-13 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_post_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='listing',
            new_name='post',
        ),
    ]
