# Generated by Django 4.1.2 on 2022-11-18 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_watchlist_listing_watchlist_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='listing',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listing',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to='auctions.listing'),
        ),
    ]
