# Generated by Django 4.1.2 on 2022-11-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_comment_listing_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo',
            field=models.URLField(blank=True),
        ),
    ]
