# Generated by Django 4.1.2 on 2022-11-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_listing_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.JSONField(max_length=256),
        ),
    ]
