# Generated by Django 4.1.2 on 2022-11-27 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_listing_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watchlist_bool',
        ),
    ]
