# Generated by Django 4.1.2 on 2022-12-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_listing_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('fashion', 'FASHION'), ('toys', 'TOYS'), ('electronics', 'ELECTRONICS'), ('home', 'HOME'), ('pet', 'PET')], max_length=20),
        ),
    ]
